
spring:
  application:
    name: gateway-service

  config:
    import: optional:configserver:http://config-server:8888

eureka:
  instance:
    hostname: api-gateway
    prefer-ip-address: false

  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/