

spring:
  application:
    name: master-service

  config:
    import: optional:configserver:http://config-server:8888

eureka:
  instance:
    hostname: master-service
    prefer-ip-address: false

  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true